name: Scheduled Workflow

on:
  schedule:
    - cron: '0 17 * * 0' # Runs every Sunday at 5 PM UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  maintenance:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Generate logs
      run: ./generate_logs.sh
    - name: Upload logs
      uses: actions/upload-artifact@v2
      with:
        name: logs
        path: ./logs